config/routes.rb
Rails.application.routes.draw do
  resources :submissions do
    member do
      put 'upVotes'
    end
    
  end

  resources :submissions, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvote, on: :member
    post :downvote, on: :member
  end

  resources :comments, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvotec, on: :member
    post :downvotec, on: :member
  end

  resources :users

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/submit', to: 'submissions#new', as: 'submit'
  get "/news", to:'submissions#index', as: 'news'
  get '/newest', to: 'submissions#newest'
  get '/ask', to: 'submissions#ask'
  get 'user_submissions', to:'submissions#usersubmissions'
  get 'user_asks', to:'submissions#userasks'
  get 'user_voted', to:'submissions#uservoted'
  get '/signout', to: 'sessions#destroy', as: 'signout'
  get '/submissions/:id/comments', to: 'submissions#submissionComments'
  get '/users/:id/submissions', to: 'submissions#apiUserSubmissions'
  get '/users/:id/comments', to: 'comments#userComments'
  # post '/comments', to: 'comments#createComment'

  

  root 'submissions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :submission
  belongs_to :user
  belongs_to :parent, class_name: 'comment', optional: true
  has_many :comments, foreign_key: :parent_id
  has_many :votecs
  validates :content, presence:true

  def upvotecs
    votecs.sum(:upvotec)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # def create
          
    #     @comment = current_user.comments.new(comment_params)
    #     if !@comment.save
    #       flash[:notice] = @comment.errors.full_messages.to_sentence
    #     end
    #     redirect_to submission_path(params[:submission_id])

    # end

    def create
      key = request.headers[:HTTP_X_API_KEY]
      tmp = nil
      us = nil
      if key
        tmp = User.where("token=?", key).first
        if tmp
          us = tmp
        end
      else 
        us = current_user
      end
      @comment = us.comments.new(comment_params)
      if @comment.content.empty?
        render :json => {:error => "The text is empty"}
      else
        @comment.save
        respond_to do |format|
          format.html {redirect_to submission_path(params[:submission_id])}
          format.json {render json: @comment, status: :created}
        end
      end
    end

  def upvotec
    @comment = Comment.find_by(id: params[:id])
    key = request.headers[:HTTP_X_API_KEY]
    tmp = nil
    us = nil
    if key
      tmp = User.where("token=?", key).first
      if tmp
        us = tmp
      end
    else 
      us = current_user
    end
      if !us.upvotecd?(@comment)
        us.upvotec(@comment)
        @s = Submission.find_by_id(@comment.submission_id)
        respond_to do |format|
            format.html { redirect_to @s }
            format.json { render json: @comment }
          end
      else
        render :json => {"Error": "Comment ja votat"}, status: :bad_request
      end
  end

  def downvotec
    @comment = Comment.find_by(id: params[:id])
    key = request.headers[:HTTP_X_API_KEY]
    tmp = nil
    us = nil
    if key
      tmp = User.where("token=?", key).first
      if tmp
        us = tmp
      end
    else 
      us = current_user
    end
    if us.upvotecd?(@comment)
      us.remove_votec(@comment)
      @s = Submission.find_by_id(@comment.submission_id)
      respond_to do |format|
          format.html { redirect_to @s }
          format.json { render json: @comment }
      end
    else
      render :json => {"Error": "No pots desvotar un Comment que no has votat"}, status: :bad_request
    end
  end

    def show
      respond_to do |format|
        format.html {render :show}
        format.json {render json: @comment}
      end
    end

    def userComments
      @user = User.find(params[:id])
      if @user.nil? 
        render :json => {"Error": "User not found"}
      else 
        @comments = Comment.where("user_id=?", params[:id]).order("created_at DESC")
        if @comments[0] == nil
          render :json => {"Error": "Comments not found"}
        else
          render json: @comments
        end
      end
    end



    private

    def comment_params
        params.require(:comment).permit(:content, :parent_id, :submission_id ).merge(submission_id: params[:submission_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<article>
    <p> <%= comment.content %> </p>
    <% if logged_in? %> 
        <% if !current_user.upvotecd?(comment)%>
            <span class="upvotec-comment">
            <%= link_to "Upvote (#{comment.upvotecs})", upvotec_comment_path(comment), method: :post %>
            <%else%>
                <%= link_to "Downvote (#{comment.upvotecs})", downvotec_comment_path(comment), method: :post %>
        </span>
        <% end %>
    <% end %>
    <small> by <%= comment.user.username %> </small>
    <% if logged_in? %>
    <a href="#" class= "comment-form-display"> reply</a>
    <div class="comment-form">       
    <%= render partial: 'comments/form', locals: {submission: comment.submission, parent: comment} %>       
    </div>
    <%end%>
    <hr />
    <div class="sub-comment">
        <%= render comment.comments.order(id: :desc) %>
    </div>
</article>


<script>
document.querySelectorAll('.comment-form-display').forEach((el) => {
    el.addEventListener('click', (ev) => {
        ev.preventDefault();
        el.nextElementSibling.style = 'display: block;'
    })
})
</script>

app/views/comments/_form.html.erb
<form action="<%= submission_comments_path(submission) %>" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="hidden" name="authenticity_token">
    <% if !parent.nil? %>
        <input type="hidden" name="comment[parent_id]" value="<%= parent.id%>">
    <%end%>
    <div>
    <% if logged_in? %>
    <textarea name="comment[content]"  rows="6" cols="20"> </textarea>
    </div>
    <input type = "submit" value="submit">
    <%end%>
    </form>