config/routes.rb
Rails.application.routes.draw do
  resources :submissions do
    member do
      put 'upVotes'
    end
    
  end

  resources :submissions, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvote, on: :member
    post :downvote, on: :member
  end

  resources :comments, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvotec, on: :member
    post :downvotec, on: :member
  end

  resources :users

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/submit', to: 'submissions#new', as: 'submit'
  get "/news", to:'submissions#index', as: 'news'
  get '/newest', to: 'submissions#newest'
  get '/ask', to: 'submissions#ask'
  get 'user_submissions', to:'submissions#usersubmissions'
  get 'user_asks', to:'submissions#userasks'
  get 'user_voted', to:'submissions#uservoted'
  get '/signout', to: 'sessions#destroy', as: 'signout'
  get '/submissions/:id/comments', to: 'submissions#submissionComments'
  get '/users/:id/submissions', to: 'submissions#apiUserSubmissions'
  get '/users/:id/comments', to: 'comments#userComments'
  # post '/comments', to: 'comments#createComment'

  

  root 'submissions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :submissions
    has_many :votes
    has_many :comments
    has_many :votecs
    has_secure_password
   
    
    def self.create_from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.username = auth['info']['first_name']
            u.email = auth['info']['email']
            u.token = auth['credentials']['token']
            u.password = SecureRandom.hex(16)
        end
    end

    def upvote(submission)
        votes.create(upvote: 1, submission: submission)
    end

    def upvoted?(submission)
        votes.exists?(upvote: 1, submission: submission)
    end
      
    def remove_vote(submission)
        votes.find_by(submission: submission).destroy
    end

    def upvotec(comment)
        votecs.create(upvotec: 1, comment: comment)
    end

    def upvotecd?(comment)
        votecs.exists?(upvotec: 1, comment: comment)
    end
      
    def remove_votec(comment)
        votecs.find_by(comment: comment).destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  # GET /users or /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @users}
    end
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @user}
    end
  end
  
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    key = request.headers[:HTTP_X_API_KEY]
    tmp = nil
    @us = nil
    if key
      tmp = User.where("token=?", key).first
      if tmp
        @us = tmp
      end
    elsif current_user
      @us = current_user
    else 
      respond_to do |format|
        format.json { head :unauthorized}
      end
    end
    if @us
      if @us == User.find_by(id: params[:id])
        respond_to do |format|
          if @us.update(user_params)
            format.html { redirect_to @us, notice: "User was successfully updated." }
            format.json { render :show, status: :ok, location: @us }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @us.errors, status: :unprocessable_entity }
          end
        end
        else 
          respond_to do |format|
            format.json { head :forbidden}
          end
      end
    else 
      respond_to do |format|
        format.json { head :forbidden}
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :uid, :provider, :about)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid %>
  </div>

  <div class="field">
    <%= form.label :provider %>
    <%= form.text_field :provider %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_field :about %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Uid</th>
      <th>Provider</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.uid %></td>
        <td><%= user.provider %></td>
        <td><%= user.about %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<background color=#088A4B>

<p >
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>Created:</strong>
  <%= @user.created_at %>
</p>



<% if current_user && current_user.id == @user.id %>

  <p>
  <strong>Email:</strong>
  <font color=#088A4B> <%= @user.email %> </font>
  </p>

  <tr><td valign="top"><strong>about:</td><td style="overflow:hidden;">
  <p>
  <%= form_for(@user) do |formu| %>
    

    <div class="field">
      
      <%= formu.text_area :about %>
    </div>
    
    <div class="actions">
      <%= formu.submit %>
    </div>

     <p>
    <strong>API-KEY:</strong>
    <font color=#088A4B> <%= @user.token %> </font>
  </p>
  <% end %>

  </textarea> 
  
  <font size="-2">
    <a href="formatdoc" tabindex="-1">
      <font color="#afafaf"></font>
    </a>
  </font> 
  </td></tr>
  </p>



<% else %>
<p>
  <strong>About:</strong>
  <%= @user.about %>
</p>

<% end %>

<background>

<%= link_to 'submissions', user_submissions_path(:user => @user.id) %>
<%= link_to 'asks', user_asks_path(:user => @user.id) %>