config/routes.rb
Rails.application.routes.draw do
  resources :submissions do
    member do
      put 'upVotes'
    end
    
  end

  resources :submissions, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvote, on: :member
    post :downvote, on: :member
  end

  resources :comments, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvotec, on: :member
    post :downvotec, on: :member
  end

  resources :users

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/submit', to: 'submissions#new', as: 'submit'
  get "/news", to:'submissions#index', as: 'news'
  get '/newest', to: 'submissions#newest'
  get '/ask', to: 'submissions#ask'
  get 'user_submissions', to:'submissions#usersubmissions'
  get 'user_asks', to:'submissions#userasks'
  get 'user_voted', to:'submissions#uservoted'
  get '/signout', to: 'sessions#destroy', as: 'signout'
  get '/submissions/:id/comments', to: 'submissions#submissionComments'
  get '/users/:id/submissions', to: 'submissions#apiUserSubmissions'
  get '/users/:id/comments', to: 'comments#userComments'
  # post '/comments', to: 'comments#createComment'

  

  root 'submissions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<ul>
  <li class="logo"><%= link_to 'HackerNews', news_path%></li>
  <li><%= link_to 'news', newest_path%></li>
  <li><a href="#threads">threads</a></li>
  <li><%= link_to 'ask', ask_path%></li>
  <li><%= link_to 'submit', submit_path%></li>
  <% if logged_in? %>
    <li style="float:right"> <%= link_to "Sign out", signout_path, id: "sign_out" %></li>
    <li style="float:right"><%= link_to current_user.username, "/users/#{current_user.id}" %> </li> 
  <% else %>
  
  <li class=boton style="float:right"><%= button_to "Login", '/auth/google_oauth2'%> </li>
  <%end%>
  
</ul>
  

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>