config/routes.rb
Rails.application.routes.draw do
  resources :submissions do
    member do
      put 'upVotes'
    end
    
  end

  resources :submissions, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvote, on: :member
    post :downvote, on: :member
  end

  resources :comments, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvotec, on: :member
    post :downvotec, on: :member
  end

  resources :users

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/submit', to: 'submissions#new', as: 'submit'
  get "/news", to:'submissions#index', as: 'news'
  get '/newest', to: 'submissions#newest'
  get '/ask', to: 'submissions#ask'
  get 'user_submissions', to:'submissions#usersubmissions'
  get 'user_asks', to:'submissions#userasks'
  get 'user_voted', to:'submissions#uservoted'
  get '/signout', to: 'sessions#destroy', as: 'signout'
  get '/submissions/:id/comments', to: 'submissions#submissionComments'
  get '/users/:id/submissions', to: 'submissions#apiUserSubmissions'
  get '/users/:id/comments', to: 'comments#userComments'
  # post '/comments', to: 'comments#createComment'

  

  root 'submissions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/submission.rb
class Submission < ApplicationRecord
    belongs_to :user
    has_many :votes
    has_many :comments
    validates :title, presence: true
    validates :url, format: { with: %r{\Ahttps?://} }, allow_blank: true, uniqueness: { case_sensitive: false }

    def upvotes
        votes.sum(:upvote)
    end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only:[:show, :edit, :update, :destroy, :upVotes, :upvote]

  # GET /submissions or /submissions.json
  def index
  #  @submissions = Submission.all
  @submissions = Submission.where.not(url: "").all.sort_by{|s| s.upvotes}.reverse
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @submissions}
      end
    end

  def ask
  #  @submissions = Submission.all
    @submissions = Submission.where(url: "").all.sort_by{|s| s.upvotes}.reverse
    respond_to do |format|
      format.html {render :ask}
      format.json {render json: @submissions}
    end
  end

  def newest
    @submissions = Submission.all.order('created_at DESC')
    respond_to do |format|
      format.html {render :newest}
      format.json {render json: @submissions}
    end
  end

  # GET /submissions/1 or /submissions/1.json
  def show
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @submission}
    end
  end

  def submissionComments
    @comments = Comment.where(submission_id: params[:id]).order("created_at DESC")
    if @comments[0] == nil
      render :json => {"Error": "Comments not found"}
    else
      render json: @comments
    end
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  def usersubmissions
      @user = User.find(params[:user])
      @submissions = Submission.where("user_id=?", params[:user]).order("created_at DESC")
      respond_to do |format|
        format.html {  render :usersubmissions}
        format.json { render json: @submission}
      end
  end

  def apiUserSubmissions
    begin
      @user = User.find(params[:id])
      if @user.nil? 
        render :json => {"Error": "User not found"}
      else 
        @submissions = Submission.where("user_id=?", params[:id]).order("created_at DESC")
        if @submissions[0] == nil
          render :json => {"Error": "Comments not found"}
        else
          render json: @submissions
        end
      end
    rescue ActiveRecord::RecordNotFound
      render :json => {"Error": "User not found"}, status: :not_found
    end
  end

  def userasks
    @user = User.find(params[:user])
    @submissions = Submission.where("user_id=?", params[:user]).order("created_at DESC")
    respond_to do |format|
      format.html {  render :userasks}
      format.json { render json: @submission}
    end
  end
 
  def uservoted
    @user = User.find(params[:user])
    @votes = Vote.where("user_id=?", params[:user])
    @submissions = Submission.where(current_user.upvoted?)
  end

  # GET /submissions/1/edit
  def edit
    
  end

  # POST /submissions or /submissions.json
  def create
    
    @submission = Submission.new(submission_params)
    key = request.headers[:HTTP_X_API_KEY]
    tmp = nil
    if key
      tmp = User.where("token=?", key).first
      if tmp
        @submission.user = tmp
      end
    else 
      @submission.user = current_user
    end
    @submission2 = Submission.where(url: submission_params[:url])
    if @submission2.exists? && !@submission2.first[:url].blank?
      respond_to do |format|
        if key
          if tmp 
            format.html {redirect_to submission_path(@submission2.first)}
            format.json {render json: @submission2.first}
          else
            format.json { head :forbidden }
          end
        elsif current_user
          format.html {redirect_to submission_path(@submission2.first)}
          format.json {render json: @submission2.first}
        else 
          format.json { head :unauthorized}
        end
      end
    else
      if !submission_params[:url].blank? && !submission_params[:text].blank?
        @submission.text = ""
        @comment = Comment.new
        @comment.content = submission_params[:text]
        @comment.user_id = @submission.user_id
       end
      respond_to do |format|
        if @submission.save
          if !submission_params[:url].blank? && !submission_params[:text].blank?
            @comment.submission_id = @submission.id
            @comment.save
          end
          format.html { redirect_to @submission, notice: "Submission was successfully created." }
          format.json { render :show, status: :created, location: @submission }
        else
          format.html { render :new, status: :unprocessable_entity }
          if tmp
            format.json { render json: @submission.errors, status: :bad_request }
          else
            format.json { head :forbidden }
          end
        end
      end
    end

  end

  def upvote
    @submission = Submission.find_by(id: params[:id])
    key = request.headers[:HTTP_X_API_KEY]
    tmp = nil
    us = nil
    if key
      tmp = User.where("token=?", key).first
      if tmp
        us = tmp
      end
    else 
      us = current_user
    end

    if !us.upvoted?(@submission)
      us.upvote(@submission)
      @submission.upVotes = @submission.upVotes + 1
      @submission.save
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: @submission }
        end
    else
      render :json => {"Error": "Submission ja votada"}, status: :bad_request
    end
  end

  def downvote
    @submission = Submission.find_by(id: params[:id])
    key = request.headers[:HTTP_X_API_KEY]
    tmp = nil
    us = nil
    if key
      tmp = User.where("token=?", key).first
      if tmp
        us = tmp
      end
    else 
      us = current_user
    end
    if us.upvoted?(@submission)
      us.remove_vote(@submission)
      @submission.upVotes = @submission.upVotes - 1
      @submission.save
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: @submission }
        end
    else
      render :json => {"Error": "No pots desvotar una submission que no has votat"}, status: :bad_request
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:title, :url, :text)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_allsubmissions.html.erb
<table>
  
  <tbody>
    <tr>
      <td>
        <% i = 1 %>
        <% @submissions.each do |submission| %>
          
          <table>
            <tbody>
              <tr>
                <td><%= i %>.</td>
                <td>
                <% if logged_in? %>
                  <% if !current_user.upvoted?(submission)%>
                    <%=link_to image_tag('/assets/arrowgray.png'), upvote_submission_path(submission), method: :post %>
                  <% else%>
                    <%=link_to image_tag('/assets/invarrowgray.png'), downvote_submission_path(submission), method: :post %>
                  <% end %>
                <% end %>
                </td>
                <td>
                  <font color="black" size="3">
                  <a style="text-decoration:none;" href=<%= submission.url %>><%= submission.title%>
                  </a>
                  </font> </font> <font color="grey" size="2">(<%= submission.url %>)</font>
                </td>
              </tr>
          </table> 
          <table>
            <tr>
                <td>
                  <font color="grey" size="2">
                    <%= submission.upvotes %> points by 
                    <%= link_to submission.user.username, "/users/#{submission.user.id}", id: "my_profile" %>
                    <a style="text-decoration:none;"><%= time_ago_in_words(submission.created_at) %> ago </a> |
                    <a style="text-decoration:none;"><%= submission.comments.size()%> <%= link_to 'comments', submission %></a> |
                    <% if current_user && current_user.id == submission.user.id %>
                      <a style="text-decoration:none;"> <%= link_to 'edit', edit_submission_path(submission) %></a> |
                      <a style="text-decoration:none;"> <%= link_to 'delete', submission, method: :delete %></a> 
                    <% end %>
                  </font>
                </td>
            </tr>
            <% i += 1 %>
            <% end %>
          </tbody>
        </table>  
      </td>
    </tr>
  </tbody>
</table>

<br>

app/views/submissions/_asks.html.erb
<table>
  
  <tbody>
    <tr>
      <td>
        <% i = 1 %>
        <% @submissions.each do |submission| %>
          <% if submission.url == ""%>
          <table>
            <tbody>
              <tr>
                <td><%= i %>.</td>
                <td>
                <% if logged_in? %>
                  <% if !current_user.upvoted?(submission)%>
                    <%=link_to image_tag('/assets/arrowgray.png'), upvote_submission_path(submission), method: :post %>
                  <% else%>
                    <%=link_to image_tag('/assets/invarrowgray.png'), downvote_submission_path(submission), method: :post %>
                  <% end %>
                <% end %>
                </td>
                <td>
                  <font color="black" size="3">
                  <a style="text-decoration:none;" href=<%= submission.url %>><%= submission.title%>
                  </a>
                  </font> </font>
                </td>
              </tr>
          </table> 
          <table>
            <tr>
                <td>
                  <font color="grey" size="2">
                    <%= submission.upvotes %> points by 
                    <%= link_to submission.user.username, "/users/#{submission.user.id}", id: "my_profile" %>
                    <a style="text-decoration:none;"><%= time_ago_in_words(submission.created_at) %> ago </a> |
                    <a style="text-decoration:none;"> <%= submission.comments.size()%> <%= link_to 'comments', submission %></a> |
                    <% if current_user && current_user.id == submission.user.id %>
                      <a style="text-decoration:none;"> <%= link_to 'edit', edit_submission_path(submission) %></a> |
                      <a style="text-decoration:none;"> <%= link_to 'delete', submission, method: :delete %></a> 
                    <% end %>
                  </font>
                </td>
            </tr>
            <% i += 1 %>
            <% end %>
            <% end %>
          </tbody>
        </table>  
      </td>
    </tr>
  </tbody>
</table>

<br>

app/views/submissions/_form.html.erb
<%= form_with(model: submission) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul> 
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "Título" %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url,  placeholder: "Url" %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text,  placeholder: "Texto" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/_submissions.html.erb
<table>
  
  <tbody>
    <tr>
      <td>
        <% i = 1 %>
        <% @submissions.each do |submission| %>
          <% if submission.url != ""%>
          <table>
            <tbody>
              <tr>
                <td><%= i %>.</td>
                <td>   
                <% if logged_in? %>
                  <% if !current_user.upvoted?(submission)%>
                    <%=link_to image_tag('/assets/arrowgray.png'), upvote_submission_path(submission), method: :post %>
                  <% else%>
                    <%=link_to image_tag('/assets/invarrowgray.png'), downvote_submission_path(submission), method: :post %>
                  <% end %>
                <% end %>
                </td>
                <td>
                  <font color="black" size="3">
                  <a style="text-decoration:none;" href=<%= submission.url %>><%= submission.title%>
                  </a>
                  </font> </font> <font color="grey" size="2">(<%= submission.url %>)</font>
                </td>
              </tr>
          </table> 
          <table>
            <tr>
                <td>
                  <font color="grey" size="2">
                    <%= submission.upvotes %> points by 
                    <%= link_to submission.user.username, "/users/#{submission.user.id}", id: "my_profile" %>       
                    <a style="text-decoration:none;"><%= time_ago_in_words(submission.created_at) %> ago </a> |
                    <a style="text-decoration:none;"> <%= submission.comments.size()%> <%= link_to 'comments', submission %></a> |
                    <% if current_user && current_user.id == submission.user.id %>
                      <a style="text-decoration:none;"> <%= link_to 'edit', edit_submission_path(submission) %></a> |
                      <a style="text-decoration:none;"> <%= link_to 'delete', submission, method: :delete %></a> 
                    <% end %>
                  </font>
                </td>
            </tr>
            <% i += 1 %>
            <% end %>
            <% end %>
          </tbody>
        </table>  
      </td>
    </tr>
  </tbody>
</table>

<br>

app/views/submissions/ask.html.erb
<p id="notice"><%= notice %></p>
<%= render 'asks'%>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  
  <tbody>
    <tr>
      <td>
        <% i = 1 %>
        <% @submissions.each do |submission| %>
          <% if submission.url != ""%>
          <table>
            <tbody>
              <tr>
                <td><%= i %>.</td>
                <td>
                <%=link_to image_tag('/assets/arrowgray.png'), upVotes_submission_path(submission), method: :put %>
                </td>
                <td>
                  <font color="black" size="3">
                  <a style="text-decoration:none;" href=<%= submission.url %>><%= submission.title%>
                  </a>
                  </font> </font> <font color="grey" size="2">(<%= submission.url %>)</font>
                </td>
              </tr>
          </table> 
          <table>
            <tr>
                <td>
                  <font color="grey" size="2">
                    <%= submission.upVotes %> points by 
                    <%= link_to submission.user.username, "/users/#{submission.user.id}", id: "my_profile" %>       
                    <a style="text-decoration:none;"><%= time_ago_in_words(submission.created_at) %> ago </a> |
                    <% if current_user && current_user.id == submission.user.id %>
                      <a style="text-decoration:none;"> <%= link_to 'edit', edit_submission_path(submission) %></a> |
                      <a style="text-decoration:none;"> <%= link_to 'delete', submission, method: :delete %></a> 
                    <% end %>
                  </font>
                </td>
            </tr>
            <% i += 1 %>
            <% end %>
            <% end %>
          </tbody>
        </table>  
      </td>
    </tr>
  </tbody>
</table>

<br>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%if logged_in? %>
    <%= render 'form', submission: @submission %>
<%else%>
    <div>
      <%= button_to "Login", '/auth/google_oauth2'%>
    </div>
<%end%>

app/views/submissions/newest.html.erb
<p id="notice"><%= notice %></p>
<%= render 'submissions'%>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @submission.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @submission.url %>
</p>

<p>
  <strong>Text:</strong>
  <%= @submission.text %>
</p>
<p>
  <strong>Comments:</strong>
  
  <%= render @submission.comments.where(parent_id: nil) %>
  <%= render partial: 'comments/form' , locals: {submission: @submission, parent: nil} %>
</p>

<% if current_user && current_user.id == @submission.user.id %>
<a style="text-decoration:none;"> <%= link_to 'edit', edit_submission_path(@submission) %></a> |
<a style="text-decoration:none;"> <%= link_to 'delete', @submission, method: :delete %></a> 
<% end %>

app/views/submissions/userasks.html.erb
<p id="notice"><%= notice %></p>
<p>
    <a><%= @user.username %>'s ask submissions</a>
</P>
<%= render 'asks'%>

app/views/submissions/usersubmissions.html.erb
<p id="notice"><%= notice %></p>
<p>
    <a><%= @user.username %>'s submissions</a>
</P>
<%= render 'submissions'%>

app/views/submissions/votedsubmissions.html.erb
<p id="notice"><%= notice %></p>
<%= render 'allsubmissions'%>